logging.level:
  org.hibernate.SQL: debug 
  org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/library
    username: root
    password: library

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8090