<?xml version="1.0"?>
<wsdl:definitions name="Students"
	  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	  xmlns:xs="http://www.w3.org/2001/XMLSchema"
	  targetNamespace="http://webservice.api.sb/soap/services/students"
	  xmlns:tns="http://webservice.api.sb/soap/services/students"
	  xmlns:types="http://webservice.api.sb/soap"
>

  <wsdl:types>
    <xsd:schema targetNamespace="http://webservice.api.sb/soap"
			      xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			      elementFormDefault="qualified"
			      attributeFormDefault="unqualified"
			      version="1.0">
		<xsd:import namespace="http://webservice.api.sb/soap" schemaLocation="students.xsd"/>
    </xsd:schema>
  </wsdl:types>

  <wsdl:message name="getStudentByIdRequest">
    <wsdl:part name="request" type="types:GetStudentByIdRequest" />
  </wsdl:message>

  <wsdl:message name="getStudentByIdResponse">
    <wsdl:part name="response"  element="types:GetStudentByIdResponse" />
  </wsdl:message>


  <wsdl:portType name="GetStudentById_PortType">
    <wsdl:operation name="getStudentById">
      <wsdl:input message="tns:getStudentByIdRequest" />
      <wsdl:output message="tns:getStudentByIdResponse" />
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="GetStudentById_SoapBinding" type="tns:GetStudentById_PortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="getStudentById">
      <soap:operation soapAction="http://webservice.api.sb/soap/services/students/getStudentById" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="GetStudentById_Service">
    <wsdl:documentation>Student service</wsdl:documentation>
    <wsdl:port name="Student_Port" binding="tns:GetStudentById_SoapBinding">
      <soap:address location="http://localhost:8080/ws/students" />
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>